// <auto-generated />
using System;
using AUDANEPAD_Integrated.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AUDANEPAD_Integrated.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200212084534_LookUp13")]
    partial class LookUp13
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Admin_Generated")
                        .HasColumnType("boolean");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Staff_Number")
                        .HasColumnType("text");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Address_City")
                        .HasColumnType("text");

                    b.Property<string>("Address_PostCode")
                        .HasColumnType("text");

                    b.Property<string>("Address_State")
                        .HasColumnType("text");

                    b.Property<string>("Address_Street")
                        .HasColumnType("text");

                    b.Property<int>("Country")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Department_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Directorate_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("Employee_Status")
                        .HasColumnType("boolean");

                    b.Property<string>("First_Name")
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("text");

                    b.Property<string>("Last_Name")
                        .HasColumnType("text");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("text");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<int>("RankStep")
                        .HasColumnType("integer");

                    b.Property<string>("Staff_Number")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_ActivityType", b =>
                {
                    b.Property<int>("Activity_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool?>("ActivityType_Status")
                        .HasColumnType("boolean");

                    b.Property<string>("Activity_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Activity_Id");

                    b.ToTable("LkUp_ActivityType");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_CommsChannel", b =>
                {
                    b.Property<int>("CommsChannel_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CommsChannel_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool?>("CommsChannel_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("CommsChannel_Id");

                    b.ToTable("LkUp_CommsChannel");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_CostCatelogue", b =>
                {
                    b.Property<int>("Cost_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Cost_Category")
                        .HasColumnType("text");

                    b.Property<string>("Cost_Code")
                        .HasColumnType("text");

                    b.Property<string>("Cost_Description")
                        .HasColumnType("text");

                    b.Property<bool>("Cost_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<float>("Unit_Cost")
                        .HasColumnType("real");

                    b.Property<string>("Unit_Of_Measure")
                        .HasColumnType("text");

                    b.HasKey("Cost_Id");

                    b.ToTable("LkUp_CostCatelogue");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_Country", b =>
                {
                    b.Property<int>("Country_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AfricanCountry")
                        .HasColumnType("integer");

                    b.Property<string>("Country_Capital")
                        .HasColumnType("text");

                    b.Property<string>("Country_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("Country_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Country_Id");

                    b.ToTable("LkUp_Country");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_DSAType", b =>
                {
                    b.Property<int>("DSA_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("DSAType_Status")
                        .HasColumnType("boolean");

                    b.Property<string>("DSA_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<float>("DSA_Value")
                        .HasColumnType("real");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("DSA_Id");

                    b.ToTable("LkUp_DSAType");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_ExtParticipantType", b =>
                {
                    b.Property<int>("Record_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Record_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Record_Id");

                    b.ToTable("LkUp_ExtParticipantType");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_FiscalYear", b =>
                {
                    b.Property<int>("Record_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Record_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Record_Id");

                    b.ToTable("LkUp_FiscalYear");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_ImplementationType", b =>
                {
                    b.Property<int>("Record_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Record_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Record_Id");

                    b.ToTable("LkUp_ImplementationType");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_LeadershipStatus", b =>
                {
                    b.Property<int>("Record_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Record_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Record_Id");

                    b.ToTable("LkUp_LeadershipStatus");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_ParticipantType", b =>
                {
                    b.Property<int>("Record_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Record_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Record_Id");

                    b.ToTable("LkUp_ParticipantType");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_PeopleType", b =>
                {
                    b.Property<int>("Record_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Record_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Record_Id");

                    b.ToTable("LkUp_PeopleType");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_ProcurementLTime", b =>
                {
                    b.Property<int>("Record_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Record_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Record_Id");

                    b.ToTable("LkUp_ProcurementLTime");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_ProcurementType", b =>
                {
                    b.Property<int>("Record_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Record_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Record_Id");

                    b.ToTable("LkUp_ProcurementType");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_ProjectScope", b =>
                {
                    b.Property<int>("Record_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Record_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Record_Id");

                    b.ToTable("LkUp_ProjectScope");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_RegionScope", b =>
                {
                    b.Property<int>("Record_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Record_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Record_Id");

                    b.ToTable("LkUp_RegionScope");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_RiskCategory", b =>
                {
                    b.Property<int>("Record_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Record_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Record_Id");

                    b.ToTable("LkUp_RiskCategory");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_RiskImpact", b =>
                {
                    b.Property<int>("Record_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Record_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Record_Id");

                    b.ToTable("LkUp_RiskImpact");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_RiskProbability", b =>
                {
                    b.Property<int>("Record_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Record_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Record_Id");

                    b.ToTable("LkUp_RiskProbability");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_RiskRTimeframe", b =>
                {
                    b.Property<int>("Record_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Record_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Record_Id");

                    b.ToTable("LkUp_RiskRTimeframe");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Strategy_Priority", b =>
                {
                    b.Property<int>("Record_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Record_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Record_Id");

                    b.ToTable("Strategy_Priority");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_ActivityType", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Activity_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_ActivityType");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_CommsChannel", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("CommsChannel_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_CommsChannel");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_CostCatelogue", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Cost_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_CostCatelogue");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_Country", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Country_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_Country");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_DSAType", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("DSA_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_DSAType");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_ExtParticipantType", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Record_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_ExtParticipantType");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_FiscalYear", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Record_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_FiscalYear");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_ImplementationType", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Record_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_ImplementationType");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_LeadershipStatus", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Record_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_LeadershipStatus");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_ParticipantType", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Record_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_ParticipantType");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_PeopleType", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Record_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_PeopleType");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_ProcurementLTime", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Record_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_ProcurementLTime");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_ProcurementType", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Record_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_ProcurementType");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_ProjectScope", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Record_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_ProjectScope");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_RegionScope", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Record_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_RegionScope");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_RiskCategory", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Record_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_RiskCategory");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_RiskImpact", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Record_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_RiskImpact");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_RiskProbability", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Record_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_RiskProbability");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_RiskRTimeframe", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Record_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_RiskRTimeframe");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_StrategyPriority", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Record_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_StrategyPriority");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AUDANEPAD_Integrated.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AUDANEPAD_Integrated.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AUDANEPAD_Integrated.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AUDANEPAD_Integrated.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
