// <auto-generated />
using System;
using AUDANEPAD_Integrated.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AUDANEPAD_Integrated.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Admin_Generated")
                        .HasColumnType("boolean");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<bool>("Ever_LoggedIn")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Staff_Number")
                        .HasColumnType("text");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Address_City")
                        .HasColumnType("text");

                    b.Property<string>("Address_PostCode")
                        .HasColumnType("text");

                    b.Property<string>("Address_State")
                        .HasColumnType("text");

                    b.Property<string>("Address_Street")
                        .HasColumnType("text");

                    b.Property<int>("Country")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Department_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Directorate_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("Employee_Status")
                        .HasColumnType("boolean");

                    b.Property<string>("First_Name")
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("text");

                    b.Property<string>("Last_Name")
                        .HasColumnType("text");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("text");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<int>("RankStep")
                        .HasColumnType("integer");

                    b.Property<string>("Staff_Number")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("TestEmail")
                        .HasColumnType("text");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_ActivityType", b =>
                {
                    b.Property<int>("Activity_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool?>("ActivityType_Status")
                        .HasColumnType("boolean");

                    b.Property<string>("Activity_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Activity_Id");

                    b.ToTable("LkUp_ActivityType");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_CommsChannel", b =>
                {
                    b.Property<int>("CommsChannel_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CommsChannel_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool?>("CommsChannel_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("CommsChannel_Id");

                    b.ToTable("LkUp_CommsChannel");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_CostCatelogue", b =>
                {
                    b.Property<int>("Cost_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Cost_Category")
                        .HasColumnType("text");

                    b.Property<string>("Cost_Code")
                        .HasColumnType("text");

                    b.Property<string>("Cost_Description")
                        .HasColumnType("text");

                    b.Property<bool>("Cost_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<float>("Unit_Cost")
                        .HasColumnType("real");

                    b.Property<string>("Unit_Of_Measure")
                        .HasColumnType("text");

                    b.HasKey("Cost_Id");

                    b.ToTable("LkUp_CostCatelogue");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_Country", b =>
                {
                    b.Property<int>("Country_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AfricanCountry")
                        .HasColumnType("integer");

                    b.Property<string>("Country_Capital")
                        .HasColumnType("text");

                    b.Property<string>("Country_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("Country_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Country_Id");

                    b.ToTable("LkUp_Country");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_DSAType", b =>
                {
                    b.Property<int>("DSA_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("DSAType_Status")
                        .HasColumnType("boolean");

                    b.Property<string>("DSA_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<float>("DSA_Value")
                        .HasColumnType("real");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("DSA_Id");

                    b.ToTable("LkUp_DSAType");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_ExtParticipantType", b =>
                {
                    b.Property<int>("Record_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Record_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Record_Id");

                    b.ToTable("LkUp_ExtParticipantType");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_FiscalYear", b =>
                {
                    b.Property<int>("Record_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Record_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Record_Id");

                    b.ToTable("LkUp_FiscalYear");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_ImplementationType", b =>
                {
                    b.Property<int>("Record_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Record_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Record_Id");

                    b.ToTable("LkUp_ImplementationType");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_IndicatorType", b =>
                {
                    b.Property<int>("Record_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Record_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Record_Id");

                    b.ToTable("LkUp_IndicatorType");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_LeadershipStatus", b =>
                {
                    b.Property<int>("Record_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Record_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Record_Id");

                    b.ToTable("LkUp_LeadershipStatus");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_MobilityLimits", b =>
                {
                    b.Property<int>("Record_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("MonthlyLimit")
                        .HasColumnType("integer");

                    b.Property<bool>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Record_Id");

                    b.ToTable("LkUp_MobilityLimits");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_ParticipantType", b =>
                {
                    b.Property<int>("Record_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Record_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Record_Id");

                    b.ToTable("LkUp_ParticipantType");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_PeopleType", b =>
                {
                    b.Property<int>("Record_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Record_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Record_Id");

                    b.ToTable("LkUp_PeopleType");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_Period", b =>
                {
                    b.Property<int>("Record_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Record_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Record_Id");

                    b.ToTable("LkUp_Period");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_ProcurementLTime", b =>
                {
                    b.Property<int>("Record_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Record_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Record_Id");

                    b.ToTable("LkUp_ProcurementLTime");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_ProcurementType", b =>
                {
                    b.Property<int>("Record_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Record_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Record_Id");

                    b.ToTable("LkUp_ProcurementType");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_Programme", b =>
                {
                    b.Property<int>("Record_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Directorate_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Division_Id")
                        .HasColumnType("integer");

                    b.Property<string>("DocPath")
                        .HasColumnType("text");

                    b.Property<string>("Record_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Record_Id");

                    b.ToTable("LkUp_Programme");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_Project", b =>
                {
                    b.Property<int>("Record_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Directorate_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Division_Id")
                        .HasColumnType("integer");

                    b.Property<string>("DocPath")
                        .HasColumnType("text");

                    b.Property<int>("Programme_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Record_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Record_Id");

                    b.ToTable("LkUp_Project");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_ProjectScope", b =>
                {
                    b.Property<int>("Record_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Record_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Record_Id");

                    b.ToTable("LkUp_ProjectScope");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_RegionScope", b =>
                {
                    b.Property<int>("Record_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Record_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Record_Id");

                    b.ToTable("LkUp_RegionScope");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_RiskCategory", b =>
                {
                    b.Property<int>("Record_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Record_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Record_Id");

                    b.ToTable("LkUp_RiskCategory");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_RiskImpact", b =>
                {
                    b.Property<int>("Record_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Record_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Record_Id");

                    b.ToTable("LkUp_RiskImpact");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_RiskProbability", b =>
                {
                    b.Property<int>("Record_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Record_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Record_Id");

                    b.ToTable("LkUp_RiskProbability");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.LkUp_RiskRTimeframe", b =>
                {
                    b.Property<int>("Record_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Record_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool?>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Record_Id");

                    b.ToTable("LkUp_RiskRTimeframe");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Strategy_KeyPerformanceArea", b =>
                {
                    b.Property<int>("Record_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Record_Name")
                        .HasColumnType("text");

                    b.Property<bool?>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<int>("StrategicPriority_Id")
                        .HasColumnType("integer")
                        .HasMaxLength(255);

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Record_Id");

                    b.ToTable("Strategy_KeyPerformanceArea");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Strategy_MTP", b =>
                {
                    b.Property<int>("Record_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Record_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool?>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Record_Id");

                    b.ToTable("Strategy_MTP");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Strategy_MTPPriorityMapping", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("MTP_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Priority_Id")
                        .HasColumnType("integer");

                    b.Property<bool?>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Strategy_MTPPriorityMapping");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Strategy_OutputIndicators", b =>
                {
                    b.Property<int>("Record_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Indicator_Type")
                        .HasColumnType("text");

                    b.Property<string>("Record_Name")
                        .HasColumnType("text");

                    b.Property<bool?>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Record_Id");

                    b.ToTable("Strategy_OutputIndicators");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Strategy_OutputIndicatorsPriorityMapping", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("KeyPerformanceArea_Id")
                        .HasColumnType("integer");

                    b.Property<int>("OutputIndicator_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Priority_Id")
                        .HasColumnType("integer");

                    b.Property<bool?>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Strategy_OutputIndicatorsPriorityMapping");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Strategy_Priority", b =>
                {
                    b.Property<int>("Record_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Record_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool?>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Record_Id");

                    b.ToTable("Strategy_Priority");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Struc_DirDivIndicators", b =>
                {
                    b.Property<int>("Record_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Directorate_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Division_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Indicator_Type")
                        .HasColumnType("text");

                    b.Property<int>("Indicator_Type_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Record_Name")
                        .HasColumnType("text");

                    b.Property<bool?>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Record_Id");

                    b.ToTable("Struc_DirDivIndicators");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Struc_DirStaffMapping", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Directorate_Id")
                        .HasColumnType("integer");

                    b.Property<int>("EmployeePK")
                        .HasColumnType("integer");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("text");

                    b.Property<bool?>("Mapping_Status")
                        .HasColumnType("boolean");

                    b.Property<bool?>("PrimaryDirectorate")
                        .HasColumnType("boolean");

                    b.Property<string>("Staff_Number")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Struc_DirStaffMapping");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Struc_Director", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Directorate_Id")
                        .HasColumnType("integer");

                    b.Property<int>("EmployeePK")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Staff_Number")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("Status")
                        .HasColumnType("boolean");

                    b.Property<int>("Status_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Struc_Director");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Struc_DirectorOIC", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Directorate_Id")
                        .HasColumnType("integer");

                    b.Property<int>("EmployeePK")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("OIC_Status")
                        .HasColumnType("text");

                    b.Property<string>("Staff_Number")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Struc_DirectorOIC");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Struc_Directorate", b =>
                {
                    b.Property<int>("Record_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Record_Name")
                        .IsRequired()
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<bool?>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Record_Id");

                    b.ToTable("Struc_Directorate");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Struc_DivHead", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Directorate_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Division_Id")
                        .HasColumnType("integer");

                    b.Property<int>("EmployeePK")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Staff_Number")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("Status")
                        .HasColumnType("boolean");

                    b.Property<int>("Status_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Struc_DivHead");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Struc_DivHeadOIC", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Directorate_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Division_Id")
                        .HasColumnType("integer");

                    b.Property<int>("EmployeePK")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("OIC_Status")
                        .HasColumnType("text");

                    b.Property<string>("ParentTransaction_Id")
                        .HasColumnType("text");

                    b.Property<string>("Staff_Number")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Struc_DivHeadOIC");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Struc_DivStaffMapping", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Directorate_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Division_Id")
                        .HasColumnType("integer");

                    b.Property<int>("EmployeePK")
                        .HasColumnType("integer");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("text");

                    b.Property<bool?>("Mapping_Status")
                        .HasColumnType("boolean");

                    b.Property<bool?>("PrimaryDivision")
                        .HasColumnType("boolean");

                    b.Property<string>("Staff_Number")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Struc_DivStaffMapping");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Struc_Division", b =>
                {
                    b.Property<int>("Record_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Directorate_Id")
                        .HasColumnType("integer")
                        .HasMaxLength(255);

                    b.Property<string>("Record_Name")
                        .HasColumnType("text");

                    b.Property<bool?>("Record_Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Record_Id");

                    b.ToTable("Struc_Division");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.System_Audit", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<string>("AuditStatement")
                        .HasColumnType("text");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("System_Audit");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_ActivityType", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Activity_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_ActivityType");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_CommsChannel", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("CommsChannel_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_CommsChannel");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_CostCatelogue", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Cost_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_CostCatelogue");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_Country", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Country_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_Country");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_DSAType", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("DSA_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_DSAType");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_ExtParticipantType", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Record_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_ExtParticipantType");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_FiscalYear", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Record_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_FiscalYear");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_ImplementationType", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Record_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_ImplementationType");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_IndicatorType", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Record_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_IndicatorType");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_LeadershipStatus", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Record_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_LeadershipStatus");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_MobilityLimits", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Record_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_MobilityLimits");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_ParticipantType", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Record_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_ParticipantType");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_PeopleType", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Record_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_PeopleType");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_Period", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Record_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_Period");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_ProcurementLTime", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Record_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_ProcurementLTime");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_ProcurementType", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Record_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_ProcurementType");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_Programme", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Directorate_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Division_Id")
                        .HasColumnType("integer");

                    b.Property<int>("MainProgramme_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_Programme");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_Project", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Directorate_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Division_Id")
                        .HasColumnType("integer");

                    b.Property<int>("MainProgramme_Id")
                        .HasColumnType("integer");

                    b.Property<int>("MainProject_Id")
                        .HasColumnType("integer");

                    b.Property<string>("TransProgramme_Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_Project");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_ProjectScope", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Record_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_ProjectScope");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_RegionScope", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Record_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_RegionScope");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_RiskCategory", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Record_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_RiskCategory");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_RiskImpact", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Record_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_RiskImpact");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_RiskProbability", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Record_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_RiskProbability");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_RiskRTimeframe", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Record_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_RiskRTimeframe");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_StrategyKeyPerformanceArea", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("StrategicKeyPerformanceArea_Id")
                        .HasColumnType("integer");

                    b.Property<string>("TransStrategicPriority_Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_StrategyKeyPerformanceArea");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_StrategyMTP", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Record_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_StrategyMTP");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_StrategyOutputIndicators", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Record_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_StrategyOutputIndicators");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_StrategyPriority", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Record_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_StrategyPriority");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_StrucDirDivIndicators", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Directorate_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Division_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Indicator_Type")
                        .HasColumnType("text");

                    b.Property<int>("Indicator_Type_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Record_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Record_Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_StrucDirDivIndicators");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_StrucDirectorate", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Record_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_StrucDirectorate");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.Trans_StrucDivision", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Division_Id")
                        .HasColumnType("integer");

                    b.Property<string>("TransDirectorate_Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("Trans_StrucDivision");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.WP_AUDAPriority", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<int>("FiscalYear_Id")
                        .HasColumnType("integer");

                    b.Property<int>("MTP_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Period_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Priority_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Project_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("WPMainRecord_id")
                        .HasColumnType("text");

                    b.HasKey("Transaction_Id");

                    b.ToTable("WP_AUDAPriority");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.WP_ApprovalStatus", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<int>("FiscalYear_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Period_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Project_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("WPMainRecord_id")
                        .HasColumnType("text");

                    b.Property<string>("WPStatusStatement")
                        .HasColumnType("text");

                    b.HasKey("Transaction_Id");

                    b.ToTable("WP_ApprovalStatus");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.WP_CountryScope", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Country_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<int>("FiscalYear_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Period_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Project_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("WPMainRecord_id")
                        .HasColumnType("text");

                    b.HasKey("Transaction_Id");

                    b.ToTable("WP_CountryScope");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.WP_DispatchCycle", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<bool?>("Dispatch_Status")
                        .HasColumnType("boolean");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<int>("FiscalYear_Id")
                        .HasColumnType("integer");

                    b.Property<bool?>("LinkToSAPExecution")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("PeriodEndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("PeriodStartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Period_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Transaction_Id");

                    b.ToTable("WP_DispatchCycle");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.WP_MTP", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<int>("FiscalYear_Id")
                        .HasColumnType("integer");

                    b.Property<int>("MTP_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Period_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Project_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("WPMainRecord_id")
                        .HasColumnType("text");

                    b.HasKey("Transaction_Id");

                    b.ToTable("WP_MTP");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.WP_MainRecord", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<string>("BarCode_Id")
                        .HasColumnType("text");

                    b.Property<bool?>("ContinentalCoverage")
                        .HasColumnType("boolean");

                    b.Property<int>("Directorate_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Division_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<int>("FiscalYear_Id")
                        .HasColumnType("integer");

                    b.Property<bool?>("LinkToSAPExecution")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("PeriodEndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("PeriodStartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Period_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Programme_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Project_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("WP_ApprovalStatus")
                        .HasColumnType("text");

                    b.Property<string>("WP_Status")
                        .HasColumnType("text");

                    b.HasKey("Transaction_Id");

                    b.ToTable("WP_MainRecord");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.WP_Mobility", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Country_Id")
                        .HasColumnType("integer");

                    b.Property<int>("FiscalYear_Id")
                        .HasColumnType("integer");

                    b.Property<double>("MobilityCost")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("MobilityEndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("MobilityStartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Period_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Project_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("WPMainRecord_id")
                        .HasColumnType("text");

                    b.Property<string>("WPMobility_Description")
                        .HasColumnType("text");

                    b.Property<string>("WPOutputActivity_Id")
                        .HasColumnType("text");

                    b.Property<string>("WPOutput_Id")
                        .HasColumnType("text");

                    b.HasKey("Transaction_Id");

                    b.ToTable("WP_Mobility");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.WP_MobilityExternalTeam", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<string>("ExternalParticipant_Description")
                        .HasColumnType("text");

                    b.Property<int>("ExternalParticipant_Id")
                        .HasColumnType("integer");

                    b.Property<int>("ExternalParticipant_Number")
                        .HasColumnType("integer");

                    b.Property<int>("FiscalYear_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PeriodEndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("PeriodStartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Period_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Project_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("WPMainRecord_id")
                        .HasColumnType("text");

                    b.Property<string>("WPMobility_id")
                        .HasColumnType("text");

                    b.Property<string>("WPOutputActivity_Id")
                        .HasColumnType("text");

                    b.Property<string>("WPOutput_Id")
                        .HasColumnType("text");

                    b.HasKey("Transaction_Id");

                    b.ToTable("WP_MobilityExternalTeam");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.WP_MobilityInternalTeam", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<int>("FiscalYear_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PeriodEndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("PeriodStartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Period_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Project_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("WPMainRecord_id")
                        .HasColumnType("text");

                    b.Property<string>("WPMobility_id")
                        .HasColumnType("text");

                    b.Property<string>("WPOutputActivity_Id")
                        .HasColumnType("text");

                    b.Property<string>("WPOutput_Id")
                        .HasColumnType("text");

                    b.HasKey("Transaction_Id");

                    b.ToTable("WP_MobilityInternalTeam");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.WP_MobilityLimit", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<int>("FiscalYear_Id")
                        .HasColumnType("integer");

                    b.Property<int>("MonthlyLimit")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PeriodEndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("PeriodStartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Period_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Project_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("WPCycle_id")
                        .HasColumnType("text");

                    b.HasKey("Transaction_Id");

                    b.ToTable("WP_MobilityLimit");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.WP_Outcomes", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<int>("FiscalYear_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Outcome")
                        .HasColumnType("text");

                    b.Property<int>("Period_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Project_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("WPMainRecord_id")
                        .HasColumnType("text");

                    b.HasKey("Transaction_Id");

                    b.ToTable("WP_Outcomes");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.WP_OutputActivities", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<double>("ActivityCost")
                        .HasColumnType("double precision");

                    b.Property<string>("ActivityDescription")
                        .HasColumnType("text");

                    b.Property<DateTime>("ActivityEndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ActivityStartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ActivityType_Id")
                        .HasColumnType("integer");

                    b.Property<double>("BaselineFinancial")
                        .HasColumnType("double precision");

                    b.Property<double>("BaselineTechnical")
                        .HasColumnType("double precision");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<int>("FiscalYear_Id")
                        .HasColumnType("integer");

                    b.Property<int>("ImplementationType_Id")
                        .HasColumnType("integer");

                    b.Property<bool?>("PartnerFunding")
                        .HasColumnType("boolean");

                    b.Property<string>("PartnerFundingDescr")
                        .HasColumnType("text");

                    b.Property<int>("Period_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Project_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("WPMainRecord_id")
                        .HasColumnType("text");

                    b.Property<string>("WPOutput_Id")
                        .HasColumnType("text");

                    b.Property<string>("WPSAPLink_Id")
                        .HasColumnType("text");

                    b.HasKey("Transaction_Id");

                    b.ToTable("WP_OutputActivities");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.WP_OutputActivityCountries", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Country_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<int>("FiscalYear_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Period_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Project_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("WPMainRecord_id")
                        .HasColumnType("text");

                    b.Property<string>("WPOutputActivity_Id")
                        .HasColumnType("text");

                    b.Property<string>("WPOutput_Id")
                        .HasColumnType("text");

                    b.HasKey("Transaction_Id");

                    b.ToTable("WP_OutputActivityCountries");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.WP_OutputBudget", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("FiscalYear_Id")
                        .HasColumnType("integer");

                    b.Property<double>("Output_BudgetAmount")
                        .HasColumnType("double precision");

                    b.Property<int>("Period_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Project_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("UtilizationPercentage")
                        .HasColumnType("double precision");

                    b.Property<string>("WPMainRecord_id")
                        .HasColumnType("text");

                    b.Property<string>("WPOutput_Id")
                        .HasColumnType("text");

                    b.Property<string>("WPSAPLink_Id")
                        .HasColumnType("text");

                    b.HasKey("Transaction_Id");

                    b.ToTable("WP_OutputBudget");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.WP_OutputIndicators", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<string>("BaselineQuanlitative")
                        .HasColumnType("text");

                    b.Property<double>("BaselineQuantitative")
                        .HasColumnType("double precision");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<int>("FiscalYear_Id")
                        .HasColumnType("integer");

                    b.Property<string>("IndicatorCategory")
                        .HasColumnType("text");

                    b.Property<string>("IndicatorType")
                        .HasColumnType("text");

                    b.Property<int>("KeyPerformanceArea_Id")
                        .HasColumnType("integer");

                    b.Property<int>("OutputIndicator_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Period_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Priority_Id")
                        .HasColumnType("integer");

                    b.Property<string>("ProjectBasedIndicatorStatement")
                        .HasColumnType("text");

                    b.Property<int>("Project_Id")
                        .HasColumnType("integer");

                    b.Property<string>("TargetQuanlitative")
                        .HasColumnType("text");

                    b.Property<double>("TargetQuantitative")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("WPMainRecord_id")
                        .HasColumnType("text");

                    b.Property<string>("WPOutput_Id")
                        .HasColumnType("text");

                    b.HasKey("Transaction_Id");

                    b.ToTable("WP_OutputIndicators");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.WP_Outputs", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<int>("FiscalYear_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Output")
                        .HasColumnType("text");

                    b.Property<int>("Period_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Project_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("WPMainRecord_id")
                        .HasColumnType("text");

                    b.Property<string>("WPSAPLink_Id")
                        .HasColumnType("text");

                    b.HasKey("Transaction_Id");

                    b.ToTable("WP_Outputs");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.WP_RegionScope", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Employee_Id")
                        .HasColumnType("integer");

                    b.Property<int>("FiscalYear_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Period_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Project_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Region_Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("WPMainRecord_id")
                        .HasColumnType("text");

                    b.HasKey("Transaction_Id");

                    b.ToTable("WP_RegionScope");
                });

            modelBuilder.Entity("AUDANEPAD_Integrated.Models.WP_SAPLink", b =>
                {
                    b.Property<string>("Transaction_Id")
                        .HasColumnType("text");

                    b.Property<int>("Directorate_Id")
                        .HasColumnType("integer");

                    b.Property<double>("SAP_BudgetAmount")
                        .HasColumnType("double precision");

                    b.Property<string>("SAP_Description")
                        .HasColumnType("text");

                    b.Property<string>("SAP_WBS")
                        .HasColumnType("text");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("WPDispatchCycle_Id")
                        .HasColumnType("text");

                    b.HasKey("Transaction_Id");

                    b.ToTable("WP_SAPLink");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AUDANEPAD_Integrated.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AUDANEPAD_Integrated.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AUDANEPAD_Integrated.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AUDANEPAD_Integrated.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
